### ISSUE TITLE
Create a CLI for installing Intercity

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/intercity-next#163]
I think the best option is to create a traveling ruby package (That way we can still keep using ruby, and no need to install stuff on the server.)

I'm currently doing some research on the subject, but stuff looks promising!

## Todo
* [x] Move config vars out of a config file and into the interface
* [x] Create a Intercity CLI bundle
* [x] Have a bash wrapper script for curling into bash for installing the CLI
* [x] Allow for setting up Lets Encrypt in the CLI

**Comment by jvanbaarsen** [comment]
This has been fixed by shipping github.com/intercity/intercity-server
