### ISSUE TITLE
Release version 0.2.0

### ISSUE THREAD

**Issue by jvanbaarsen** [intercity/intercity-next#201]
* [x] Make sure CHANGELOG is up-to-date
* [x] Make sure intercity-docker is pulling correct IC version
* [x] Make sure all documentation is up-to-date
* [x] Update VERSION file in IC-Next
* [x] Push to `0-2-stable` branch
* [x] Push `0-2-stable` to `stable` branch
* [x] Ensure Intercity-server is installing correct IC version

**Comment by jvanbaarsen** [comment]
Version 0.2.0 Has been released
